### ISSUE TITLE
Some changes and improvements 

### ISSUE THREAD

**Issue by preitychib** [wrench1815/productapi#4]
- [x] **Availability**: It is returning false when the product is neither out of stock nor upcoming.

- [x]  **Specifications**: 

We need to _reduce length of field to 255 characters_ in
                  General >Network
                  Camra>Rear Camra
                  Camra>Front Camra
                  Video>Rear Camra Video Quality
we need some fields to be _optional_ 
                  Memory >External Memory
                  Battery>Standby
                  Battery>Talktime
                  Body>BodyType

- [x] Change data type to  _string_

                  Connectivity >Bluetooth

**Comment by wrench1815** [comment]
The Availability showing false is not if the item is available or not, it is the field that table dumps in logs
